// This file has been generated by Specta. DO NOT EDIT.

export type TextFileType = { type: "json" } | { type: "manifestJson" } | { type: "plainText" } | { type: "markdown" }

export type EditorRequest = { type: "text"; data: TextEditorRequest }

export type ProjectSettings = { gameInstall: string | null }

export type EditorEvent = { type: "text"; data: TextEditorEvent }

export type GameBrowserRequest = { type: "setEnabled"; data: boolean } | { type: "newTree"; data: { game_description: string; entries: GameBrowserEntry[] } }

export type FileBrowserRequest = { type: "create"; data: { path: string; is_folder: boolean } } | { type: "delete"; data: string } | { type: "rename"; data: { old_path: string; new_path: string } } | { type: "select"; data: string | null } | { type: "newTree"; data: { base_path: string; files: ([string, boolean])[] } }

export type SettingsRequest = { type: "initialise"; data: { game_installs: GameInstall[]; settings: AppSettings } } | { type: "changeProjectSettings"; data: ProjectSettings }

export type Request = { type: "tool"; data: ToolRequest } | { type: "editor"; data: EditorRequest } | { type: "global"; data: GlobalRequest }

export type ToolRequest = { type: "fileBrowser"; data: FileBrowserRequest } | { type: "gameBrowser"; data: GameBrowserRequest } | { type: "settings"; data: SettingsRequest }

export type ToolEvent = { type: "fileBrowser"; data: FileBrowserEvent } | { type: "gameBrowser"; data: GameBrowserEvent } | { type: "settings"; data: SettingsEvent }

export type GameBrowserEntry = { hash: string; path: string; hint: string }

export type GlobalRequest = { type: "errorReport"; data: { error: string } } | { type: "setWindowTitle"; data: string } | { type: "createTab"; data: { id: string; name: string; editor_type: EditorType; file: string | null } } | { type: "selectTab"; data: string } | { type: "setTabUnsaved"; data: { id: string; unsaved: boolean } }

export type TextEditorEvent = { type: "initialise"; data: { id: string } } | { type: "updateContent"; data: { id: string; content: string } }

export type GameVersion = "h1" | "h2" | "h3"

export type GameInstall = { version: GameVersion; platform: string; path: string }

export type GlobalEvent = { type: "loadWorkspace"; data: string } | { type: "selectTab"; data: string } | { type: "removeTab"; data: string } | { type: "saveTab"; data: string }

export type EditorType = { type: "nil" } | { type: "text"; data: { file_type: TextFileType } } | { type: "qnentity" } | { type: "qnpatch" }

export type FileBrowserEvent = { type: "select"; data: string | null } | { type: "create"; data: { path: string; is_folder: boolean } } | { type: "delete"; data: string } | { type: "rename"; data: { old_path: string; new_path: string } }

export type Event = { type: "tool"; data: ToolEvent } | { type: "editor"; data: EditorEvent } | { type: "global"; data: GlobalEvent }

export type GameBrowserEvent = { type: "select"; data: string | null } | { type: "search"; data: string }

export type AppSettings = { extractModdedFiles: boolean; gameFileExtensionsPath: string | null }

export type SettingsEvent = { type: "initialise" } | { type: "changeGameInstall"; data: string | null } | { type: "changeExtractModdedFiles"; data: boolean } | { type: "changeGFEPath"; data: string | null }

export type TextEditorRequest = { type: "replaceContent"; data: { id: string; content: string } } | { type: "setFileType"; data: { id: string; file_type: TextFileType } }

