// This file has been generated by Specta. DO NOT EDIT.

export type GameBrowserEntry = { hash: string; path: string; hint: string }

export type FileBrowserRequest = { type: "create"; data: { path: string; is_folder: boolean } } | { type: "delete"; data: string } | { type: "rename"; data: { old_path: string; new_path: string } } | { type: "newTree"; data: { base_path: string; files: ([string, boolean])[] } }

export type ToolRequest = { type: "fileBrowser"; data: FileBrowserRequest } | { type: "gameBrowser"; data: GameBrowserRequest } | { type: "settings"; data: SettingsRequest }

export type GameBrowserEvent = { type: "select"; data: string | null } | { type: "search"; data: string }

export type FileBrowserEvent = { type: "select"; data: string | null } | { type: "create"; data: { path: string; is_folder: boolean } } | { type: "delete"; data: string } | { type: "rename"; data: { old_path: string; new_path: string } }

export type AppSettings = { extractModdedFiles: boolean; gameFileExtensionsPath: string | null }

export type GlobalRequest = { type: "errorReport"; data: { error: string } } | { type: "setWindowTitle"; data: string }

export type Event = { type: "tool"; data: ToolEvent } | { type: "global"; data: GlobalEvent }

export type Request = { type: "tool"; data: ToolRequest } | { type: "global"; data: GlobalRequest }

export type SettingsRequest = { type: "initialise"; data: { game_installs: GameInstall[]; settings: AppSettings } } | { type: "changeProjectSettings"; data: ProjectSettings }

export type SettingsEvent = { type: "initialise" } | { type: "changeGameInstall"; data: string | null } | { type: "changeExtractModdedFiles"; data: boolean } | { type: "changeGFEPath"; data: string | null }

export type GameVersion = "h1" | "h2" | "h3"

export type GlobalEvent = { type: "loadWorkspace"; data: string }

export type GameInstall = { version: GameVersion; platform: string; path: string }

export type GameBrowserRequest = { type: "setEnabled"; data: boolean } | { type: "newTree"; data: { game_description: string; entries: GameBrowserEntry[] } }

export type ToolEvent = { type: "fileBrowser"; data: FileBrowserEvent } | { type: "gameBrowser"; data: GameBrowserEvent } | { type: "settings"; data: SettingsEvent }

export type ProjectSettings = { gameInstall: string | null }

