/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function event(event: Event) {
    return invoke()<null>("event", { event })
}

export type ToolEvent = { type: "fileBrowser"; data: FileBrowserEvent }
export type FileBrowserEvent = { type: "select"; data: null } | { type: "create"; data: null } | { type: "delete"; data: null } | { type: "move"; data: null } | { type: "rename"; data: null }
export type Event = { type: "tool"; data: ToolEvent } | { type: "global"; data: GlobalEvent }
export type GlobalEvent = { type: "workspaceLoaded"; data: { path: string } }
